/*  ChemVantage - A Java web application for online learning
*   Copyright (C) 2012 ChemVantage LLC
*   
*    This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.chemvantage.chem4ap;

import static com.googlecode.objectify.ObjectifyService.ofy;

import java.util.Date;
import java.util.List;
import java.util.Random;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;

/**
 * Nonce (Number Used Once) entity for OAuth and LTI authentication security.
 * 
 * Manages one-time use nonce values to protect OAuth 1.0 and LTI authentication flows
 * against replay attacks and eavesdropping. Each nonce represents a unique identifier
 * submitted exactly once during an authentication transaction.
 * 
 * Security Architecture:
 * - Nonce Validation: Each nonce can only be used once; second use is rejected
 * - Replay Attack Prevention: Attackers cannot reuse captured authentication requests
 * - Eavesdropping Protection: Random nonce values prevent message prediction
 * - Automatic Expiration: Nonces expire after 90 minutes; old nonces purged from datastore
 * 
 * OAuth 1.0 Integration:
 * - oauth_nonce parameter in OAuth signature base string
 * - Server-side verification that same nonce not reused
 * - Combined with oauth_timestamp for time-window protection
 * - Required for LTI launches from LMS platforms
 * 
 * LTI Protocol Usage:
 * - LTI 1.0/1.1 include nonce in OAuth signature (oauth_nonce)
 * - LTI 1.3 uses different security (OpenID Connect with JWT)
 * - Server validates nonce uniqueness for each LTI launch
 * - Prevents copycat login attacks from captured credentials
 * 
 * Generation:
 * - Combines two Random long values converted to hexadecimal
 * - Results in 32-character hex string (collision-resistant)
 * - Seeded with current system time for unpredictability
 * 
 * Storage:
 * - Stored in Datastore as @Entity with id field = nonce string
 * - Created timestamp indexed for efficient expiration queries
 * - Single record per unique nonce value
 * 
 * Lifecycle:
 * - Generated by caller on launch request
 * - Submitted in oauth_nonce parameter
 * - Validated with isUnique() method
 * - Persisted if valid and new
 * - Automatically deleted after 90-minute validity window
 * 
 * Datastore Management:
 * - Automatic cleanup of expired nonces on each validation
 * - No manual garbage collection needed
 * - Keeps datastore size bounded despite high-volume launches
 * 
 * @author ChemVantage
 * @version 1.0
 * @see LTIRequest for OAuth validation context
 * @see Deployment for OAuth provider entities
 */
@Entity
public class Nonce {
	// Nonce validity and generation constants
	/** Nonce validity interval: 90 minutes in milliseconds (90 * 60 * 1000) */
	private static final long NONCE_VALIDITY_MILLIS = 5400000L;
	
	/**
	 * Unique nonce identifier string (32-character hex value).
	 * Generated by combining two random long values.
	 * Used as primary key in datastore.
	 * Can only be used once; second submission triggers rejection.
	 */
	@Id String id;
	
	/**
	 * Timestamp when this nonce was created.
	 * Indexed field for efficient expiration queries.
	 * Used to automatically purge nonces older than validity window.
	 * Updated on nonce creation; never modified after initial save.
	 */
	@Index Date created;
	
	/**
	 * Default constructor for Objectify entity instantiation.
	 * Creates nonce with no arguments; id and created fields set to null.
	 * Called by datastore framework during entity load operations.
	 * Should not be called directly by application code.
	 */
	Nonce() {}
	
	/**
	 * Creates new Nonce with specified identifier and current timestamp.
	 * 
	 * Constructor is package-private to restrict instantiation to this class only.
	 * Called internally by isUnique() after validation succeeds.
	 * Sets created field to current system time for expiration tracking.
	 * 
	 * @param id the unique nonce identifier string (typically 32-char hex value)
	 */
	Nonce(String id) {
		this.id = id;
		this.created = new Date();
	}
	
	/**
	 * Generates a unique, unpredictable nonce string for OAuth authentication.
	 * 
	 * Algorithm:
	 * - Creates Random instance seeded with current time
	 * - Generates two random long values (unpredictable)
	 * - Converts each to hexadecimal string representation
	 * - Concatenates to form 32-character hex string
	 * - Result: collision-resistant, cryptographically suitable for OAuth
	 * 
	 * Format:
	 * - Each long converts to 16 hexadecimal characters (64-bit value)
	 * - Total length: 32 hex characters
	 * - Example: "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
	 * 
	 * Usage:
	 * - Called by application code to generate OAuth request nonce
	 * - Result submitted in oauth_nonce parameter
	 * - Later validated with isUnique() method
	 * 
	 * Performance:
	 * - String concatenation uses StringBuilder internally (efficient)
	 * - Random generation very fast (microseconds)
	 * - No datastore operations; purely in-memory
	 * 
	 * @return unique nonce string suitable for OAuth authentication flows
	 */
	static String generateNonce() {
		Random random = new Random(new Date().getTime());
		long firstRandomValue = random.nextLong();
		long secondRandomValue = random.nextLong();
		String firstHash = Long.toHexString(firstRandomValue);
		String secondHash = Long.toHexString(secondRandomValue);
		return firstHash + secondHash;
	}

	/**
	 * Validates that a nonce value is unique and hasn't been used before.
	 * 
	 * Validation Sequence:
	 * 1. Check that nonce is not null or empty (required)
	 * 2. Calculate 90-minute expiration boundary
	 * 3. Delete all nonces older than validity window
	 * 4. Check if nonce already exists in datastore
	 * 5. If new, persist nonce with current timestamp
	 * 6. Return success/failure indicator
	 * 
	 * Replay Attack Prevention:
	 * - Each nonce can only exist once in datastore
	 * - Second submission of same nonce is rejected
	 * - Attacker cannot reuse captured authentication request
	 * - Combined with timestamp validation for complete protection
	 * 
	 * Automatic Cleanup:
	 * - Expired nonces purged from datastore on each validation
	 * - Prevents database unbounded growth
	 * - Ensures strict 90-minute validity window
	 * - No manual garbage collection required
	 * 
	 * Datastore Operations:
	 * - Load: Query for existing nonce by id
	 * - Save: Persist new nonce if validation succeeds
	 * - Delete: Bulk delete expired nonces older than window
	 * - All operations use .now() for synchronous execution
	 * 
	 * Error Handling:
	 * - Throws IllegalArgumentException if nonce is null or empty
	 * - Returns false if nonce already exists (replay attack)
	 * - Returns true if nonce is new and persisted
	 * - Datastore exceptions propagate to caller
	 * 
	 * Thread Safety:
	 * - Not explicitly synchronized (Google Cloud Datastore handles atomicity)
	 * - Datastore transactions ensure only one client persists each nonce
	 * - Race conditions unlikely due to unique id constraint
	 * 
	 * Performance Characteristics:
	 * - Query for existence: ~10-50ms depending on datastore load
	 * - Cleanup operation: O(n) where n = expired nonces (typically small)
	 * - Save operation: ~10-30ms for new nonce persistence
	 * - Total: ~50-150ms per isUnique() call (acceptable for auth path)
	 * 
	 * Usage Example:
	 * <pre>
	 * String nonce = Nonce.generateNonce();  // Create unique nonce
	 * if (Nonce.isUnique(nonce)) {
	 *     // Nonce validated; proceed with authentication
	 * } else {
	 *     // Nonce replay attack detected; reject request
	 * }
	 * </pre>
	 * 
	 * @param nonce the nonce string to validate for uniqueness
	 * @return true if nonce is new and has been stored; false if already used
	 * @throws IllegalArgumentException if nonce is null or empty string
	 * @see #generateNonce() for nonce creation
	 * @see Deployment for OAuth provider context where nonce is used
	 */
	public static boolean isUnique(String nonce) {
		if (nonce == null || nonce.isEmpty()) throw new IllegalArgumentException("Nonce value is required and cannot be empty.");
		
		Date now = new Date();
		Date oldest = new Date(now.getTime() - NONCE_VALIDITY_MILLIS);  // 90 minutes ago

		// delete all Nonce objects older than the validity interval
		List<Key<Nonce>> expired = ofy().load().type(Nonce.class).filter("created <", oldest).keys().list();
		if (expired.size() > 0) ofy().delete().keys(expired);
		
		// check to see if a Nonce with the specified id already exists in the database
		if (ofy().load().type(Nonce.class).id(nonce).now() != null) return false;  // nonce already used
		
		// store a new Nonce object in the datastore with the unique nonce string
		ofy().save().entity(new Nonce(nonce)).now();
		
		return true;
	}
/*	
	public static boolean isUnique(String nonce, String timestamp) {
		// This method provides a level of security for OAuth launches for LTI
		// by verifying that oauth_nonce strings are submitted only once
		// This protects against eavesdropping and copycat login attacks
		
		Date now = new Date();
		Date oldest = new Date(now.getTime()-interval); // converts seconds to millis

		try {
			//check the timestamp to ensure this is a new launch (within half of the interval)
			Date stamped = new Date(Long.parseLong(timestamp)*1000);  // millis since Jan 1, 1970 00:00 UTC
			if (Math.abs(stamped.getTime()-now.getTime()) > interval/2) throw new Exception();  // out of submission interval
			
			// delete all Nonce objects older than the interval
			List<Key<Nonce>> expired = ofy().load().type(Nonce.class).filter("created <",oldest).keys().list();
			if (expired.size() > 0) ofy().delete().keys(expired);
			
			// check to see if a Nonce with the specified id already exists in the database
			if (ofy().load().type(Nonce.class).id(nonce).now() != null) throw new Exception(); // if nonce exists
			
			// store a new Nonce object in the datastore with the unique nonce string
			ofy().save().entity(new Nonce(nonce)).now();
			
			return true;
		} catch (Exception e) {
			return false;
		}
	}
*/
}